export const adminConstants = {
  APPROVE_CAMPAIGN_REQUEST: "APPROVE_CAMPAIGN_REQUEST",
  APPROVE_CAMPAIGN_SUCCESS: "APPROVE_CAMPAIGN_SUCCESS",
  APPROVE_CAMPAIGN_FAILURE: "APPROVE_CAMPAIGN_FAILURE",

  REJECT_CAMPAIGN_REQUEST: "REJECT_CAMPAIGN_REQUEST",
  REJECT_CAMPAIGN_SUCCESS: "REJECT_CAMPAIGN_SUCCESS",
  REJECT_CAMPAIGN_FAILURE: "REJECT_CAMPAIGN_FAILURE",

  GET_CAMPAIGN_REQUEST: "GET_CAMPAIGN_REQUEST",
  GET_CAMPAIGN_SUCCESS: "GET_CAMPAIGN_SUCCESS",
  GET_CAMPAIGN_FAILURE: "GET_CAMPAIGN_FAILURE",

  UPDATE_CAMPAIGN_REQUEST: "UPDATE_CAMPAIGN_REQUEST",
  UPDATE_CAMPAIGN_SUCCESS: "UPDATE_CAMPAIGN_SUCCESS",
  UPDATE_CAMPAIGN_FAILURE: "UPDATE_CAMPAIGN_FAILURE",

  DELETE_CAMPAIGN_REQUEST: "DELETE_CAMPAIGN_REQUEST",
  DELETE_CAMPAIGN_SUCCESS: "DELETE_CAMPAIGN_SUCCESS",
  DELETE_CAMPAIGN_FAILURE: "DELETE_CAMPAIGN_FAILURE",

  RELEASE_FUND_REQUEST: "RELEASE_FUND_REQUEST",
  RELEASE_FUND_SUCCESS: "RELEASE_FUND_SUCCESS",
  RELEASE_FUND_FAILURE: "RELEASE_FUND_FAILURE",

  GET_INVESTORS_REQUEST: "GET_INVESTORS_REQUEST",
  GET_INVESTORS_SUCCESS: "GET_INVESTORS_SUCCESS",
  GET_INVESTORS_FAILURE: "GET_INVESTORS_FAILURE",

  UPDATE_INVESTOR_REQUEST: "UPDATE_INVESTOR_REQUEST",
  UPDATE_INVESTOR_SUCCESS: "UPDATE_INVESTOR_SUCCESS",
  UPDATE_INVESTOR_FAILURE: "UPDATE_INVESTOR_FAILURE",

  DELETE_INVESTOR_REQUEST: "DELETE_INVESTOR_REQUEST",
  DELETE_INVESTOR_SUCCESS: "DELETE_INVESTOR_SUCCESS",
  DELETE_INVESTOR_FAILURE: "DELETE_INVESTOR_FAILURE",

  GET_CREATORS_REQUEST: "GET_CREATORS_REQUEST",
  GET_CREATORS_SUCCESS: "GET_CREATORS_SUCCESS",
  GET_CREATORS_FAILURE: "GET_CREATORS_FAILURE",

  UPDATE_CREATOR_REQUEST: "UPDATE_CREATOR_REQUEST",
  UPDATE_CREATOR_SUCCESS: "UPDATE_CREATOR_SUCCESS",
  UPDATE_CREATOR_FAILURE: "UPDATE_CREATOR_FAILURE",

  DELETE_CREATOR_REQUEST: "DELETE_CREATOR_REQUEST",
  DELETE_CREATOR_SUCCESS: "DELETE_CREATOR_SUCCESS",
  DELETE_CREATOR_FAILURE: "DELETE_CREATOR_FAILURE",

  DASHBOARD_REQUEST: "DASHBOARD_REQUEST",
  DASHBOARD_SUCCESS: "DASHBOARD_SUCCESS",
  DASHBOARD_FAILURE: "DASHBOARD_FAILURE",

  WEBDETAILS_ADDUPDATE_REQUEST: "WEBDETAILS_ADDUPDATE_REQUEST",
  WEBDETAILS_ADDUPDATE_SUCCESS: "WEBDETAILS_ADDUPDATE_SUCCESS",
  WEBDETAILS_ADDUPDATE_FAILURE: "WEBDETAILS_ADDUPDATE_FAILURE",

  GET_WEBDETAILS_REQUEST: "GET_WEBDETAILS_REQUEST",
  GET_WEBDETAILS_SUCCESS: "GET_WEBDETAILS_SUCCESS",
  GET_WEBDETAILS_FAILURE: "GET_WEBDETAILS_FAILURE",
};
