export const campaignConstants = {
  CREATE_CAMPAIGN_REQUEST: "CREATE_CAMPAIGN_REQUEST",
  CREATE_CAMPAIGN_SUCCESS: "CREATE_CAMPAIGN_SUCCESS",
  CREATE_CAMPAIGN_FAILURE: "CREATE_CAMPAIGN_FAILURE",

  UPDATE_CAMPAIGN_REQUEST: "UPDATE_CAMPAIGN_REQUEST",
  UPDATE_CAMPAIGN_SUCCESS: "UPDATE_CAMPAIGN_SUCCESS",
  UPDATE_CAMPAIGN_FAILURE: "UPDATE_CAMPAIGN_FAILURE",

  GETALL_CAMPAIGN_REQUEST: "GETALL_CAMPAIGN_REQUEST",
  GETALL_CAMPAIGN_SUCCESS: "GETALL_CAMPAIGN_SUCCESS",
  GETALL_CAMPAIGN_FAILURE: "GETALL_CAMPAIGN_FAILURE",

  GETMINE_CAMPAIGN_REQUEST: "GETMINE_CAMPAIGN_REQUEST",
  GETMINE_CAMPAIGN_SUCCESS: "GETMINE_CAMPAIGN_SUCCESS",
  GETMINE_CAMPAIGN_FAILURE: "GETMINE_CAMPAIGN_FAILURE",

  GETINVESTED_CAMPAIGN_REQUEST: "GETINVESTED_CAMPAIGN_REQUEST",
  GETINVESTED_CAMPAIGN_SUCCESS: "GETINVESTED_CAMPAIGN_SUCCESS",
  GETINVESTED_CAMPAIGN_FAILURE: "GETINVESTED_CAMPAIGN_FAILURE",

  GETFEATURED_CAMPAIGN_REQUEST: "GETFEATURED_CAMPAIGN_REQUEST",
  GETFEATURED_CAMPAIGN_SUCCESS: "GETFEATURED_CAMPAIGN_SUCCESS",
  GETFEATURED_CAMPAIGN_FAILURE: "GETFEATURED_CAMPAIGN_FAILURE",

  GETEDITORPICK_CAMPAIGN_REQUEST: "GETEDITORPICK_CAMPAIGN_REQUEST",
  GETEDITORPICK_CAMPAIGN_SUCCESS: "GETEDITORPICK_CAMPAIGN_SUCCESS",
  GETEDITORPICK_CAMPAIGN_FAILURE: "GETEDITORPICK_CAMPAIGN_FAILURE",

  INVEST_CAMPAIGN_REQUEST: "INVEST_CAMPAIGN_REQUEST",
  INVEST_CAMPAIGN_SUCCESS: "INVEST_CAMPAIGN_SUCCESS",
  INVEST_CAMPAIGN_FAILURE: "INVEST_CAMPAIGN_FAILURE",
};
