export const chatConstants = {
  GET_CHAT_REQUEST: "GET_CHAT_REQUEST",
  GET_CHAT_SUCCESS: "GET_CHAT_SUCCESS",
  GET_CHAT_FAILURE: "GET_CHAT_FAILURE",

  GET_CHATS_REQUEST: "GET_CHATS_REQUEST",
  GET_CHATS_SUCCESS: "GET_CHATS_SUCCESS",
  GET_CHATS_FAILURE: "GET_CHATS_FAILURE",

  CREATE_CHAT_REQUEST: "CREATE_CHAT_REQUEST",
  CREATE_CHAT_SUCCESS: "CREATE_CHAT_SUCCESS",
  CREATE_CHAT_FAILURE: "CREATE_CHAT_FAILURE",

  SEND_MESSAGE_REQUEST: "SEND_MESSAGE_REQUEST",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",
};
