export const userConstants = {
    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',

    COMPLETE_INVESTOR_PROFILE_REQUEST: 'COMPLETE_INVESTOR_PROFILE_REQUEST',
    COMPLETE_INVESTOR_PROFILE_SUCCESS: 'COMPLETE_INVESTOR_PROFILE_SUCCESS',
    COMPLETE_INVESTOR_PROFILE_FAILURE: 'COMPLETE_INVESTOR_PROFILE_FAILURE',

    COMPLETE_CREATOR_PROFILE_REQUEST: 'COMPLETE_CREATOR_PROFILE_REQUEST',
    COMPLETE_CREATOR_PROFILE_SUCCESS: 'COMPLETE_CREATOR_PROFILE_SUCCESS',
    COMPLETE_CREATOR_PROFILE_FAILURE: 'COMPLETE_CREATOR_PROFILE_FAILURE',

    GLOBAL_SEARCH_REQUEST: 'GLOBAL_SEARCH_REQUEST',
    GLOBAL_SEARCH_SUCCESS: 'GLOBAL_SEARCH_SUCCESS',
    GLOBAL_SEARCH_FAILURE: 'GLOBAL_SEARCH_FAILURE',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

    UPDATE_INVESTOR_PROFILE_REQUEST: 'UPDATE_INVESTOR_PROFILE_REQUEST',
    UPDATE_INVESTOR_PROFILE_SUCCESS: 'UPDATE_INVESTOR_PROFILE_SUCCESS',
    UPDATE_INVESTOR_PROFILE_FAILURE: 'UPDATE_INVESTOR_PROFILE_FAILURE',

    UPDATE_CREATOR_PROFILE_REQUEST: 'UPDATE_CREATOR_PROFILE_REQUEST',
    UPDATE_CREATOR_PROFILE_SUCCESS: 'UPDATE_CREATOR_PROFILE_SUCCESS',
    UPDATE_CREATOR_PROFILE_FAILURE: 'UPDATE_CREATOR_PROFILE_FAILURE',
}